sudo: required
services:
  - docker

before_install:
  - docker build -t avinashd30/docker-react-project -f Dockerfile.dev .

script:
  - docker run avinashd30/docker-react-project npm run test -- --coverage


